### ISSUE TITLE
Discussion regarding newline between `title` and `subtitle` and divisor management

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/rtables#411]
I think it is better to leave it as it is because if we introduce that new line as a standard in the code, the user will not be able to take it out if he does not want it. Of course, this can be overcome by using the title variable directly. I argue that the only thing that is impossible to do with the current state of things is to add a horizontal divisor where needed (and take it out where not). My proposition was to add a specific string that is detected and used. This goes well with the wonderful functionality of using vectors of strings instead of single strings that you @gmbecker implemented. This would encourage also its use above the uncomfortable `\n`. In general, I did not see many tables with more separators than the ones that the table has, while the newline divisors are usually highly custom and in the end, I would avoid forcing it on the user. I think though that aesthetically the divisors are necessary between the referential footnotes and the other footnotes as it is. 

NB: spacing in the ref footnotes can be weird and It is not clear to me how to change its behavior there. For example:
![Screenshot 2022-10-07 122326](https://user-images.githubusercontent.com/11279768/194532483-9deb74c5-8182-4b86-baa6-d0d87b42fb01.png)

Here I would swap the empty lines or add two of them, before and after. I am not sure how to do it though.

**Comment by gmbecker** [comment]
https://github.com/insightsengineering/formatters/blob/main/R/tostring.R#L233 @Melkiades that is where the referential footnotes are emitted during printing, so thats where adding a line after them would probably go. Care is needed to make sure all the "number of lines stuff takes up" bits (pagination) are updated though.

Generally I agree about the title/subtitle thing. That change has been reverted (for now), because it was too close to the release anyway, and I do agree that it needs more discussion (the same goes for any change in the referential footnote vertical spacing, but we can prepare for it by having that discussion)
