### ISSUE TITLE
replace default page_break from "\s\n" to "\f"

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rtables#530]
requested by Liming in https://github.com/insightsengineering/rlistings/pull/78

**Comment by shajoezhu** [comment]
closing this issue. as we will refine it with another request later

**Comment by gmbecker** [comment]
So @shajoezhu  @clarkliming `\f` does not render in R (or here, as it turns out) as a newline:

directly cut and pasted:

```
> cat("hi\fthere")
hithere> 
```

image of what R shows:
![Screen Shot 2023-03-27 at 1 57 07 PM](https://user-images.githubusercontent.com/908721/228064842-18fee446-916e-4d30-ae74-e29032a0efb2.png)


Which, again, means we need to talk about this more and figure out exactly what the best thing to do is _**before**_ we make any changes to the defaults.

**Comment by clarkliming** [comment]
in Rstudio,  `\f` will refresh the output; in terminal, it also print as a line break at least

different terminals have different results. The good thing is, if you open the text file in word, it will help you create the page break

**Comment by gmbecker** [comment]
We are not going to do something in an r package that only works well in
Rstudio. That would just be poor design in our part

**Comment by gmbecker** [comment]
Thinking about this more, the stated use-case - pasting into a word document, those page breaks are either a) already going to be in the right place because the paginated sections of the table fill exactly one page, in which case we don't need the `\f` to force a page return, or b) they won't be in the right place (e.g., because the page size and margins were correct but the table does not start at the beginning of a page in the word document), in which case we don't want an additional page return to be forced there.

Consider this really bad mockup i'm writing while very tired:

table:
```
line1 
line2
line3
line4
line5
line6
line7
```

Page length (after accounting for margins and everything): 4 lines

Case 1: 

Paginate to 4 lpp, in sync with page:

With force page break

```
line1
line2
line3
line4
```
~natural page break~~forced page break~
```
line5
line6
line7
```

Without forced page break:


```
line1
line2
line3
line4
```
~natural page break~
```
line5
line6
line7
```


Case2:
 paginated to lpp2


```
line1
line2
```
~forced page break~
```
line3
line4
```
~forced page break~
```
line5
line6
```
~forced page break~

So here our pages are only 2 lines long in our resulting word document. Thats bad


Case 3
lpp 4 but starts in the middle of the page:

```
outer text
outer text
line1
line2
```
~natural line break~
```
line3
line4
```
~forced page break~
```
line5
line6
line7
```

So thats...not right. It isn't what we want, making the page break show up magically in word documents doesn't actually make the page break...occur in the right location. And if it *is* occuring in the right location, the `\f` isn't gonna do anything.

**Comment by gmbecker** [comment]
Closing this as it is no longer planned afaik (cc @shajoezhu )
