### ISSUE TITLE
pagination: `lpp` and `cpp` default values and the help page

### ISSUE THREAD

**Issue by wwojciech** [insightsengineering/rtables#535]
https://github.com/Roche/rtables/blob/19b02b047469adc6c4ef173c631bdc51381cc501/R/tt_paginate.R#L691

I think the default is `missing`. Also similar comment fot `cpp`. Can we simply specify `lpp = 70` and `cpp = NULL ` as a default function's args? This would allow for simplification of this if-else clause which is a bit involved now: https://github.com/Roche/rtables/blob/19b02b047469adc6c4ef173c631bdc51381cc501/R/tt_paginate.R#L715

**Comment by gmbecker** [comment]
@wwojciech you are correct, although if you look slightly lower you'll see that missing is transformed to NULL, so in practice these are identical.

Either way, good catch, please make a small PR to change that.

**Comment by wwojciech** [comment]
> @wwojciech you are correct, although if you look slightly lower you'll see that missing is transformed to NULL, so in practice these are identical.
> 
> Either way, good catch, please make a small PR to change that.

Thanks @gmbecker. If you are ok with this, I will raise it after I finish with https://github.com/insightsengineering/rlistings/issues/43, and then will change it in both these places.

**Comment by gmbecker** [comment]
@wwojciech So looking a little deeper its slightly more complicated (and should be in `rlistings` too:

So the reason that `lpp` and `cpp` no longer have defaults, is because `page_type` does have a default (`letter` and that dictates the default `lpp` and `cpp` values).

That documentation predates the addition of the page stuff. Please make a patch that specifies that if they are not set they are inferred from font and page information if specified. (either by page type, which happens by default now, or by page dimensions).

**Comment by wwojciech** [comment]
Sure, thanks @gmbecker I will check it carefully.

**Comment by wwojciech** [comment]
@gmbecker, @shajoezhu asked to assign some low priority to this so, I will send it to Backlog if you do not mind, and I start working on this after I have not, other, high-priority issue assigned to me.

**Comment by Melkiades** [comment]
I think it is better to keep track of things on the main board. I added it to the backlog there instead of the overall backlog that we do not keep too much track of. Feel free to revert this change if you do not agree with it

**Comment by gmbecker** [comment]
This is superceded by the design changes that occured in the pagination and exporter migration #631
