### ISSUE TITLE
`trim_zero_rows` is disconnected from documentation

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/rtables#562]
This function is not documented in a vignette and it is missing examples. I think it should be under `trim_rows`.

**Comment by edelarua** [comment]
@gmbecker,

The `trim_zero_rows` function does not operate as expected in my tests - it currently only removes zero *integer* rows (since the function specifies that all row values must match `0L`), which typically occur only in tables as discrete variable counts. This could be remedied by updating the function code, but I'm not sure this function is still necessary since there are several better alternatives such as `prune_table(prune_zeros_only)`, `trim_rows(all_zero)`, etc. 

I would recommend leaving the function as-is for now and deprecating at some point instead. The function is not used in any `tern`/`chevron`/`tlg-catalog` code.

**Comment by Melkiades** [comment]
I would start deprecation cycle then
