### ISSUE TITLE
`Viewer` output missing horizontal line after header

### ISSUE THREAD

**Issue by edelarua** [insightsengineering/rtables#572]
As described below, the horizontal line following the header in `rtable` objects that is included in the ASCII output is not included in the `Viewer` output, or `as_html` output.

> Observed that the ASCII output includes horizontal line displayed between header and body but using Viewer() does not display the line.
> 
> ASCII
> ![image](https://user-images.githubusercontent.com/40777373/217109310-afd69ed2-3d4d-418c-b377-8c762a48c78e.png)
> 
> Viewer()
> ![image](https://user-images.githubusercontent.com/40777373/217109439-649cac5e-93ba-49b4-a44f-9e00d76fef06.png)
> 
> Was thinking that the hline might also be missing in teal output since Viewer() is also html. this is admittedly trivial. ;-)
> 
> _Originally posted by @npaszty in https://github.com/insightsengineering/chevron/issues/385#issuecomment-1419961395_
>

**Comment by gmbecker** [comment]
I believe the initial design intent is that the horizontal line is not needed because the header space is differentiated by color and bolding @edelarua @npaszty

That said I don't really feel strongly about this one way or another and honestly have not done much at all to the HTML rendering logic in my multiple years on the project.

**Comment by npaszty** [comment]
@gmbecker 
this was feedback to dev team from a chevron template UAT.
when I described as trivial that was directed at level of importance not as to whether it is a trivial fix. ;-).
so for my part it is definitely a backlog item.
