### ISSUE TITLE
 `internal_methods {rtables}` should be more informative and structured

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/rtables#574]
At the moment this documentation is not structured, as it has ~50 generics and functions without specific indication of their behavior.  In particular, I was looking for the information (I am well aware of) that the function `rtables::nrow` is only counting the number of rows in the content table and not the header, but it was not easy to access, i.e. I did not find it. I think the `internal_methods` documentation has a lot of VERY useful and used functions that will benefit greatly from more partition and grouping, examples, and linking with other functions such as `propose_column_widths` which is fundamental for horizontal pagination.

**Comment by gmbecker** [comment]
So this is a little confusing. `nrow` does not take into account column names for any method I know about, including the `data.frame` and `matrix` ones that everyone is going to think about when you just say "nrow", so I would have thought the current intentional behavior (not taking top_left or column label/structure information into account) would be expected and self-explanatory.

Also, that documentation is called _internal_ methods for a reason, its not intended for end-user consumption.  It basically only exists because R CMD check complains about undocumented methods for S4 generics, even when the generic or the method in question is not exported.

**Comment by Melkiades** [comment]
I am closing this as we discussed. It would entail changing the API making these not exported and we do not need to do it atm. It could be an action item for the future to trim down exported functions that are meant to be internals (`@keywords internal`). I think the ones that have that should not be exported. @shajoezhu fyi for the not-to-soon future
