### ISSUE TITLE
Support sorting of tables with part of the section not created (not empty table) (`sort_at_path`)

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/rtables#625]
currently `sort_at_path` directly gives error when table is not of correct structure.
example:

```r
adae <- data.frame(
  USUBJID = factor(c(1,1,2), levels = c(1,2)),
  ACTARM = factor(c('A','A','B'), levels = c("A", "B")),
  AEDECOD = factor(c('term 1', 'term 2', 'term 3'), levels = sprintf("term %s", 1:10)),
  STUDYID = factor(c('a','a','a'), levels = c("a")),
  AEBODSYS = factor(c('bodsys 1', 'bodsys 2', 'bodsys 1'),levels = sprintf("bodsys %s", c(1:3)))
)

adsl <- data.frame(
  USUBJID = factor(c(1, 2), levels = c(1,2)),
  ACTARM = factor(c("A", "B"), levels = c("A", "B"))
)
lyt <- basic_table() %>%
  split_cols_by(var = "ACTARM") %>%
  add_colcounts() %>%
  overall_col('aaa') %>%
  summarize_num_patients("USUBJID") %>%
  split_rows_by(
    "AEBODSYS",
    child_labels = "visible",
    nested = TRUE,
    split_fun = rtables::drop_split_levels,
    label_pos = "topleft",
    split_label = 'label'
  ) %>%
  summarize_num_patients(
    var = "USUBJID",
    .stats = c("unique", "nonunique"),
    .labels = c(
      unique = "Total number of patients with at least one adverse event",
      nonunique = "Total number of events"
    )
  ) %>%
  count_occurrences(
    vars = "AEDECOD",
    .indent_mods = -1L,
    drop = TRUE
  )
  
tbl1 <- build_table(lyt, adae, alt_counts_df = adsl)

sort_at_path(
  tbl1,
  c("AEBODSYS"),
  scorefun = cont_n_allcols
)

tbl2 <- build_table(lyt, adae[0, ], alt_counts_df = adsl)

sort_at_path(
  tbl2,
  c("AEBODSYS"),
  scorefun = cont_n_allcols
)
```

with same layout, different data (empty data vs full data), the generated tlg is different. sorting lead to issues on second table. This make it difficult to programmtically sort these tables (when input data changes)

**Comment by Melkiades** [comment]
> currently sort_at_path directly gives error when table is not of correct structure.

Should it be more informative?

> with same layout, different data (empty data vs full data), the generated tlg is different. sorting lead to issues on second table. This make it difficult to programmtically sort these tables (when input data changes)

A degenerative table as tbl2 does not have anything to sort under AEBODSYS so it is reasonably giving an error

I feel that sorting empty tables is not something we should support or programmatically encounter in unit testing. I will anyway add this to the current empty-table discussion

**Comment by gmbecker** [comment]
So there are two things going on here. The first is that this is arguably a buglet, because sorting the empty set should, in principle, be a null op. 

That said, whether or not it can be sorted, that is a degenerate table, because it has a subtable that has no children,  and so a bunch of other things are likely to not work, as we've discussed. Doing anything with a degenerate table, even things that happen to work, is currently unsupported. 

If we are going to support degenerate tables (which you seem to really want, even though I remain very skeptical of their value in practice) then that feature needs to be planned, resourced, and  attacked head on, as described in #613 as @Melkiades pointed out. @clarkliming @shajoezhu

**Comment by gmbecker** [comment]
AFAIK, this is mitigated fully by `sanitize_table_struct` which when called on a table, guarantees a non-degenerate table is returned for which sort should always work (absent other bugs or issues)
