### ISSUE TITLE
Consider validating output of build_table

### ISSUE THREAD

**Issue by gmbecker** [insightsengineering/rtables#661]
likely using `assert_valid_table( , warn_only = TRUE)` which would warn at build time when degenerate tables are created, but still return them to the end user.

This will likely cause warnings in `tern`, but they won't be false positives, they'll be places where tern is currently not doing the right thing (e.g., generating all rows with `summarize_row_groups` rather than having `analyze` calls)

@BFalquet @clarkliming @shajoezhu @edelarua @Melkiades @ayogasekaram

**Comment by BFalquet** [comment]
maybe better to not include it in the `build_table` function so that we can handle the error/message how we want (save in log, create an error, etc...). I think that in our workflow philosophy, we would rather assert the structure of the built table in a postprocessing step where we would also offer the option to sanitize the table (if possible).

**Comment by BFalquet** [comment]
@gmbecker I tested the proposed solution (`sanitize_table_struct`, `rtables::assert_valid_table`) and i am very happy with the result so far. I think it fits well our need, thank you very much.

**Comment by Melkiades** [comment]
Also for me, this is a great way to put in place a safe-net for degenerate tables.

**Comment by gmbecker** [comment]
Superseded by #679
