### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/rtables#672]
This is current autovalidate report outcome:
```
Consistency checks failed:
 - requirement #0.57 'Objects exported from other packages' is not covered by any test
 - requirement #0.87 'Trim Zero Rows' is not covered by any test
 - [autovalidateutils] ERROR: checking installed package size ... NOTE
  installed size is  6.9Mb
  sub-directories of 1Mb or more:
    bootstrap   1.6Mb
    doc         1.0Mb
    help        2.8Mb
    R           1.3Mb
ERROR: Validation was not successful!
```

Please address the two requirements regarding test coverage. You should be able to find relevant links with logs in our CI notification room.
I have followed-up separately to relax requirement about the package size since there is nothing really wrong with this.

**Comment by gmbecker** [comment]
@pawelru I don't have any idea what this is on about. `trim_zero_rows` is, in fact, covered by a test, despite being deprecated...

https://github.com/insightsengineering/rtables/blob/1a526387a01e010c805c89f146b537d0c6e316fd/tests/testthat/test-sort-prune.R#L159-L162

Also the other issue, the symbols in "Objects re-exported from another package" are ... re-exported from another package, namely the formatters package (over my very strenuous objections, as it happens). 

`export_as_txt` (the only symbol in that help topic) should not need to be tested here, since it is tested there, but in point of fact, it IS tested quite extensively in the rtables tests, see

https://github.com/insightsengineering/rtables/blob/1a526387a01e010c805c89f146b537d0c6e316fd/tests/testthat/test-exporters.R#L3

and the 108 lines that follow it.

**Comment by gmbecker** [comment]
cc @dgkf-roche

**Comment by pawelru** [comment]
Thanks @gmbecker. Based on your message it looks to be a false positive - same thing happen in https://github.com/insightsengineering/tern/issues/995. 
I hope we can find the root-cause (or workaround) because currently we have red autovalidate tests as well as this would require explanations in the upcoming autovalidate submission (whenever it happens).

**Comment by gmbecker** [comment]
@pawelru @shajoezhu can this issue be closed? I believe (and think I've shown) that the coverage portions of this report is purely false-positive.

**Comment by shajoezhu** [comment]
Hi @gmbecker , I think we can close this one now. trim_zero_rows is deprecated. and the other one is a false positive. Thanks!
