### ISSUE TITLE
why the order of columns changed after setting ref_groups

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/rtables#707]
in the following example, the ref_group is always put in the left-most column.

```
basic_table() %>%
  split_cols_by("Species", ref_group = "virginica") %>%
  analyze("Sepal.Length") %>%
  build_table(iris)
```

This means that if we want to have consistent output, we **have to** put placebo arm in the left. This should be re-considered to provide the flexibility

**Comment by gmbecker** [comment]
This is intentional (ie "its a feature"). The reasoning is that I didn't (and don't) think having a reference/control group appear in the middle of the list of facets doesn't make sense from a table-reading perspective. 

In light of this, `rtables` always places the reference group first amongst its direct siblings. It could have been last, or even configurable between first and last, but that did not seem worth the complexity at the time.

Note, though, that like virtually all aspects of faceting, you can (should be able to) forcibly override this with a custom split function. In this case you'd use the postprocessing portion of `make_split_fun` to reorder the facets once they are created.

**Comment by shajoezhu** [comment]
Hi @gmbecker , I was wondering if there is an example for " postprocessing portion of make_split_fun to reorder the facets once they are created." maybe we could have a vignette for this too?

**Comment by gmbecker** [comment]
@shajoezhu that is the example that appears in `?make_split_fun`

**Comment by Melkiades** [comment]
> Hi @gmbecker , I was wondering if there is an example for " postprocessing portion of make_split_fun to reorder the facets once they are created." maybe we could have a vignette for this too?

```r
reorder_facets <- function(splret, spl, fulldf, ...) {
    # browser() if you enter here the order of splret seems already correct
    ord <- order(names(splret$values))
    make_split_result(splret$values[ord],
                      splret$datasplit[ord],
                      splret$labels[ord])
}

basic_table() %>%
    split_cols_by("Species", ref_group = "virginica", split_fun = make_split_fun(post = list(reorder_facets))) %>%
    analyze("Sepal.Length") %>%
    build_table(iris)
```
and I get the following:
```
       setosa   versicolor   virginica
——————————————————————————————————————
Mean    5.01       5.94        6.59   
Warning messages:
1: In .fixupvals(ret) :
  Got a partinfo list with values that are already SplitValue objects and non-null extras element. This shouldn't happen
2: In .fixupvals(ret) :
  Got a partinfo list with values that are already SplitValue objects and non-null extras element. This shouldn't happen
```
The warning is duplicated for the duplicated split. I do not know why the order of the split in the split function seems identical to this second output before sorting and I do not know why the warning fires up

**Comment by gmbecker** [comment]
@shajoezhu I believe this issue can be closed as wontfix afterthe above pull request is merged in to get rid of the superfluous warning.
