### ISSUE TITLE
questions about drop_split_levels and trim_levels_in_facets documentation closed on StackOverflow - questions persist

### ISSUE THREAD

**Issue by adcascone** [insightsengineering/rtables#904]
Hello,

I have opened StackOverflow questions about the [`drop_split_levels()`](https://stackoverflow.com/questions/78769748/more-information-needed-about-the-drop-split-levels-function-in-the-rtables-r?noredirect=1#comment138881245_78769748
) and [`trim_levels_in_facets()`](https://stackoverflow.com/questions/78770534/more-information-needed-about-the-trim-levels-in-facets-variable-in-the-rtable
) functions, but they have been closed on the forum without responses. As such, I've attached the same questions here. 

-- `drop_split_levels()` -- 
More details are needed to explain what the drop_split_levels() function is doing in the rtables documentation/"Split functions" reference site (https://insightsengineering.github.io/rtables/latest-tag/reference/split_funcs.html#ref-examples).

It is unclear what this function does based on the example and associated output.

![image](https://github.com/user-attachments/assets/78a48fef-a078-47d9-b488-abfa6e876571)
It would additionally be helpful to include more examples with various function arguments specified.

-- `trim_levels_in_facets()` -- 
More details are needed to explain the use cases of the trim_levels_in_facets() function in the rtables documentation/"Trim levels of another variable from each facet (post-processing split step)" reference site (https://insightsengineering.github.io/rtables/latest-tag/reference/trim_levels_in_facets.html.

It would be additionally helpful to provide example code and outputs to further clarify the use cases of this function.

-- 
It is possible that StackOverflow is not the best way for users to ask specific questions about package documentation, since these types of questions are flagged as needing 'details or clarity.' 

Thank you! 
Arianna C.

**Comment by gmbecker** [comment]
Well those are less questions about how it works and more claims about changes that should be made to the documentation, so I'm not sure they belong on stack overflow rather than here (though do whatever @shajoezhu / @Melkiades say they prefer). 

That said to address your actual complaint, I suppose they are a bit sparse, though having written them, drop_split_levels' name, in particular,  was intended intended to be self describing: it drops (ie doesn't create) facets for unobserved levels of a factor, analogous to `droplevels`  from base R or the forcats equivalent `fct_drop`.

What is happening in the example is that DM actually has 4 levels for the SEX variable, but 2 of them ("U", and "UNDIFFERENTIATED") are unobserved:

```
> table(DM$SEX)

               F                M                U UNDIFFERENTIATED 
             187              169                0                0 
```
Without using drop_spjlit_levels, there would be 4 row facets instead of just the two for F and M.


trim_levels_in_facets, again, kind of does what it says on the tin, more specifically what it says in the help subject title: Trim levels of another variable from each facet (post-processing split step). It removes unobserved levels of a second variable ("innervar") independently from each facet, so that if a level is observed within, e.g., arm A but not arb B, you'd only get that level within the arm A facet. That said I agree that the documentation there is lacking, as it there is no example that uses it that I'm immediately seeing. The same goes for `trim_levels_in_group` which is just bundled up with the other canned split function instead of getting its own help like `trim_levels_to_map` (or perhaps being combined with it).  Assuming that happens `trim_levels_in_group` and `trim_levels_in_facets` should link to eachother as well. 

Another fairly large documentation issue (that likely should be its own issue) is that I don't think the custom split functions blurb belongs in the split functions help anymore as users should never be manually constructing those anymore, and should instead be using `make_split_fun`.

**Comment by Melkiades** [comment]
@adcascone Stackoverflow is usually very keen on the format of the question, and asking only to improve documentation is not a well-formatted question for them. If you ask with a specific example to explain the various differences between split functions, for example, it is already better. In general, on Stackoverflow, the "I want to do this but can't for now, can you help?" format is the preferred format. I understand your frustration about the closing, but don't worry—it takes time to understand when to post on Stackoverflow or here, and I am already taking action on your issues!! :)

I think all your doubts about default split functions are legitimate, and they are also missing some relevant examples/tests (hence the bug you found). I am reorganising it and adding dedicated descriptions and tests to all of them in the linked PR ;)

Thank you for filing these issues! I wanted to improve these docs since a bit ;)

**Comment by adcascone** [comment]
@gmbecker @Melkiades I appreciate your time and replies! 

Thanks for providing more insight into both the drop_split_levels and trim_levels_in_facets functions, clarifying the best places to ask different types of questions, and adding detail to the documentation. 

Arianna
